name: c3d
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.0.0=pyhd8ed1ab_0
  - arrow=1.2.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backoff=2.2.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - blessed=1.19.1=pyhe4f9e05_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cachecontrol=0.12.11=py39h06a4308_1
  - certifi=2023.7.22=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cleo=2.0.1=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.4.1=pyhd8ed1ab_0
  - cryptography=41.0.2=py39h22a60cf_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=10.2.89=hfd86e86_1
  - dateutils=0.6.12=py_0
  - dbus=1.13.6=he372182_0
  - deepdiff=5.8.1=pyhd8ed1ab_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - dulwich=0.21.3=py39h5eee18b_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - expat=2.2.10=h9c3ff4c_0
  - fastapi=0.99.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.9.0=pyh1a96a4e_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - h11=0.14.0=pyhd8ed1ab_0
  - html5lib=1.1=pyh9f0ad1d_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - inquirer=3.1.3=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=py39h06a4308_0
  - joblib=1.2.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - keyring=23.13.1=py39hf3d152e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.2.10=0
  - libcurand=10.3.3.141=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lightning=2.0.8=pyhd8ed1ab_0
  - lightning-cloud=0.5.37=pyhd8ed1ab_0
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - numpy=1.25.2=py39h5f9d8c6_0
  - numpy-base=1.25.2=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.10=h7f8727e_2
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - p7zip=15.09=h2d50403_4
  - packaging=23.1=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pillow=9.4.0=py39h6a678d5_0
  - pip=23.2.1=py39h06a4308_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=py39h06a4308_0
  - poetry=1.4.0=py39h06a4308_0
  - poetry-core=1.5.1=py39h06a4308_0
  - poetry-plugin-export=1.3.0=py39h4849bfd_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.8=py39h5eee18b_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py39h06a4308_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - python-build=0.10.0=pyhd8ed1ab_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python-installer=0.6.0=py39h06a4308_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda10.2_cudnn7.6.5_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-lightning=2.0.8=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - rapidfuzz=2.13.7=py39h417a72b_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_0
  - requests-toolbelt=0.10.1=pyhd8ed1ab_0
  - rich=13.5.1=pyhd8ed1ab_0
  - scikit-learn=1.3.0=py39h1128e8f_0
  - scipy=1.11.1=py39h5f9d8c6_0
  - secretstorage=3.3.3=py39hf3d152e_1
  - setuptools=68.0.0=py39h06a4308_0
  - shellingham=1.5.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.41.2=h5eee18b_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - sympy=1.11.1=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.1=pyha770c72_0
  - torchaudio=0.12.1=py39_cu102
  - torchmetrics=1.1.1=pyhd8ed1ab_0
  - torchtriton=2.0.0=py39
  - torchvision=0.13.1=py39_cu102
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - trove-classifiers=2023.8.7=pyhd8ed1ab_0
  - typing-extensions=4.7.1=py39h06a4308_0
  - typing_extensions=4.7.1=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py39h06a4308_0
  - uvicorn=0.23.2=py39hf3d152e_0
  - virtualenv=20.17.1=py39hf3d152e_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.2=pyhd8ed1ab_0
  - websockets=10.4=py39h5eee18b_1
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - appdirs==1.4.4
    - docker-pycreds==0.4.0
    - gitdb==4.0.10
    - gitpython==3.1.36
    - iniconfig==2.0.0
    - opencv-python==4.8.0.76
    - pathtools==0.1.2
    - pluggy==1.3.0
    - protobuf==4.24.3
    - pytest==7.4.2
    - sentry-sdk==1.31.0
    - setproctitle==1.3.2
    - smmap==5.0.0
    - wandb==0.15.10
